resolver: nightly-2024-05-22
packages:
  - .
ghc-options:
  "$locals": -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-deriving-strategies -Wmissing-export-lists -Wmissing-exported-signatures -Wmissing-home-modules -Wpartial-fields -Wprepositive-qualified-module -Wredundant-constraints -Wunused-binds -Wunused-packages -Wunused-type-patterns -Wno-deprecations -Wno-unticked-promoted-constructors
extra-deps:
  - env-guard-0.2@sha256:99b89cde1ed6d599880dfbc72b2c9a75ced57b7800a70dcb57d3e3e89e42184c,1312
  - text-display-0.0.5.2@sha256:6e6a5bf1c83dfa6c34692ed5d8ea87f1bd385984309b42c302f2156f4d82477b,2670
  - git: https://github.com/tbidne/algebra-simple.git
    commit: f8590486ec0fc66acf7db20308e1ed6993a52151
  - git: https://github.com/tbidne/bounds.git
    commit: f93b202c9d154b25b42b048570cf6648451aa577
  - git: https://github.com/tbidne/exception-utils.git
    commit: 9ecb81e4a16f62736dbe7f90cb1983e7212b0c0f
  - git: https://github.com/tbidne/fs-utils.git
    commit: 5406cea74491f382478e70734535c62fe6deef7d
  - git: https://github.com/tbidne/monad-effects.git
    commit: 8021f9a0855e644d91b73e6b2bcf20406ebbebb8
    subdirs:
      - lib/effects-async
      - lib/effects-env
      - lib/effects-fs
      - lib/effects-ioref
      - lib/effects-optparse
      - lib/effects-stm
      - lib/effects-time
      - lib/effects-terminal
      - lib/effects-thread
      - lib/effects-typed-process
      - lib/effects-unix-compat
  - git: https://github.com/tbidne/relative-time.git
    commit: b3be9b3b904059671ef07dbcbb11b8c04d50ddde
  - git: https://github.com/tbidne/si-bytes.git
    commit: df01a076966e7fe9af8cc49bb438078a14a8d951
  - git: https://github.com/tbidne/smart-math.git
    commit: 9bd570201445904d12d0e0b792f171d02e6f361e
