resolver: nightly-2022-07-07
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
    -Wno-unticked-promoted-constructors
extra-deps:
- env-guard-0.2@sha256:59410eed9b9ddbd115760a59c7170927320d8612e414701d323a0c8985c97523,1251
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- strict-io-0.2.2@sha256:1cc96f9a123a919ff9ee479f740cbc9fa9edf7c8ac65334de3fdce07638949ed,1012
- git: https://github.com/tbidne/algebra-simple.git
  commit: 5d9288b1e2149a1bb6db28d694c5528c0aef3cbd
- git: https://github.com/tbidne/byte-types.git
  commit: da898995e2a96d6993c5771883a04894c5455f4d
- git: https://github.com/tbidne/relative-time.git
  commit: debaa2523b3b58afc84e9cb1dab0d3af3ff332cd
flags:
  refined:
    aeson: false
    quickcheck: false
nix:
  shell-file: nix/stack.nix
