resolver: nightly-2022-10-11
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
    -Wno-unticked-promoted-constructors
extra-deps:
- env-guard-0.2@sha256:59410eed9b9ddbd115760a59c7170927320d8612e414701d323a0c8985c97523,1251
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- refined-0.7@sha256:3e1119816dad5f638d104256742d8763beb6b987044190da333ab7b63f85c934,2837
- strict-io-0.2.2@sha256:1cc96f9a123a919ff9ee479f740cbc9fa9edf7c8ac65334de3fdce07638949ed,1012
- git: https://github.com/tbidne/algebra-simple.git
  commit: 2c8a79e8d3bf67c99e4851c557bf68a44c512307
- git: https://github.com/tbidne/bounds.git
  commit: 004f03aec46f29069fd0bf5115a384cd2b3141b3
- git: https://github.com/tbidne/byte-types.git
  commit: be3e764d76c530fd3641c133ed2d53adfc8f046d
- git: https://github.com/tbidne/monad-effects.git
  commit: b3d1b6b414d9a0561da5ed529a9ff663a0345270
  subdirs:
  - monad-callstack
  - monad-fs
  - monad-ioref
  - monad-stm
  - monad-terminal
  - monad-thread
  - monad-time
- git: https://github.com/tbidne/relative-time.git
  commit: 3bd5549074da8b6dba1660e6d01f92812cefb9c2
flags:
  refined:
    aeson: false
    quickcheck: false
nix:
  shell-file: nix/stack.nix
